# Generated by Django 4.2.7 on 2024-02-20 15:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, unique=True)),
                ('time', models.TimeField()),
                ('place', models.CharField(max_length=255)),
                ('frequency', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7)])),
                ('estimated_time', models.PositiveSmallIntegerField(default=120, validators=[django.core.validators.MaxValueValidator(120)])),
                ('start_from', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_pleasant', models.BooleanField(default=False)),
                ('reward', models.CharField(blank=True, max_length=255, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_habit', to='habit.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
