# Generated by Django 4.2.7 on 2024-03-30 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'verbose_name': 'Habit', 'verbose_name_plural': 'Habits'},
        ),
        migrations.AlterField(
            model_name='habit',
            name='action',
            field=models.CharField(max_length=255, unique=True, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='estimated_time',
            field=models.PositiveSmallIntegerField(default=120, verbose_name='Time to Perform'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_learned',
            field=models.BooleanField(default=False, verbose_name='Is Learned'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Is Public'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(max_length=255, verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_habit', to='habit.habit', verbose_name='Linked Habit'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reward'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_from',
            field=models.DateField(auto_now_add=True, verbose_name='Start From'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
